# Generated by Django 5.2.7 on 2025-12-20 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
        ('Salons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='Salons.salonprofile'),
        ),
    ]
