from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import NotificationViewSet

# 1. Initialize the Router
router = DefaultRouter()

# 2. Register the ViewSet
# This creates /notifications/ and /notifications/{id}/
router.register(r'', NotificationViewSet, basename='notification')

# 3. Define the urlpatterns
urlpatterns = [
    # This includes all the routes generated by the router
    path('', include(router.urls)),
]