# Generated by Django 5.2.7 on 2025-12-20 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0002_initial'),
        ('Salons', '0001_initial'),
        ('Vendor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='Vendor.individualvendorprofile'),
        ),
        migrations.AddField(
            model_name='availabilityexception',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability_exceptions', to='Salons.salonprofile'),
        ),
        migrations.AddField(
            model_name='availabilityexception',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability_exceptions', to='Vendor.individualvendorprofile'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salon_portfolio', to='Salons.salonprofile'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_portfolio', to='Vendor.individualvendorprofile'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['date'], name='Category_av_date_18730b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='availabilityexception',
            unique_together={('salon', 'date'), ('vendor', 'date')},
        ),
    ]
