# Generated by Django 5.2.7 on 2025-12-21 22:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'verbose_name_plural': 'Availabilities'},
        ),
        migrations.RemoveIndex(
            model_name='availability',
            name='Category_av_date_18730b_idx',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='date',
        ),
        migrations.AddField(
            model_name='availability',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0),
        ),
        migrations.AlterField(
            model_name='availability',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
