# Generated by Django 5.2.7 on 2025-12-21 22:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0004_alter_availability_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
