# Generated by Django 5.2.7 on 2026-01-30 10:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0006_alter_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='category_imsage',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
