# Generated by Django 5.2.7 on 2026-01-30 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0007_servicecategory_category_imsage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicecategory',
            old_name='category_imsage',
            new_name='category_image',
        ),
    ]
