from rest_framework import serializers

class SubAccountSerializer(serializers.Serializer):
    account_bank = serializers.IntegerField(default = '035')
    account_number = serializers.IntegerField(required = True,)
    business_name = serializers.CharField(max_length=150)
    business_email = serializers.EmailField()
    business_mobile = serializers.IntegerField()

    

    


class PaymentInitSerializer(serializers.Serializer):
    booking_id = serializers.UUIDField(
        help_text="The ID of the booking to pay for."
    )

class PaymentLinkResponseSerializer(serializers.Serializer):
    status = serializers.CharField()
    message = serializers.CharField()
    link = serializers.URLField(help_text="The Flutterwave checkout URL.")

class WithdrawalRequestSerializer(serializers.Serializer):
    amount = serializers.DecimalField(max_digits=12, decimal_places=2)
    # This is a unique string generated by the mobile app for this specific click
    request_id = serializers.CharField(max_length=100, help_text="This is a unique string generated by the mobile app for this specific click")