from rest_framework import serializers
from .models import Wallet, Transaction
from django.db.models import Sum
from drf_spectacular.utils import extend_schema_field
from drf_spectacular.types import OpenApiTypes

class SubAccountSerializer(serializers.Serializer):
    account_bank = serializers.IntegerField(default = '035')
    account_number = serializers.IntegerField(required = True,)
    business_name = serializers.CharField(max_length=150)
    business_email = serializers.EmailField()
    business_mobile = serializers.IntegerField()

    

    


class PaymentInitSerializer(serializers.Serializer):
    booking_id = serializers.UUIDField(
        help_text="The ID of the booking to pay for."
    )

class PaymentLinkResponseSerializer(serializers.Serializer):
    status = serializers.CharField()
    message = serializers.CharField()
    # transaction_id = serializers.UUIDField()
    link = serializers.URLField(help_text="The Flutterwave checkout URL.")

class WithdrawalRequestSerializer(serializers.Serializer):
    amount = serializers.DecimalField(max_digits=12, decimal_places=2)
    # This is a unique string generated by the mobile app for this specific click
    request_id = serializers.CharField(max_length=100, help_text="This is a unique string generated by the mobile app for this specific click")

from rest_framework import serializers
from .models import Wallet, Transaction

class TransactionSerializer(serializers.ModelSerializer):
    class Meta:
        model = Transaction
        fields = ["id", "amount", "tx_type", "status", "tx_ref", "flw_ref", "created_at", "booking_id" ]

class WalletSerializer(serializers.ModelSerializer):
    # We include the last 5 transactions for a "Quick View" on the dashboard
    recent_transactions = serializers.SerializerMethodField()
    total_earned = serializers.SerializerMethodField()
    

    class Meta:
        model = Wallet
        fields = ["available_balance", "pending_balance", "total_earned", "recent_transactions"]

    @extend_schema_field(TransactionSerializer)
    def get_recent_transactions(self, obj):
        txs = Transaction.objects.filter(wallet=obj).order_by("-created_at")[:5]
        return TransactionSerializer(txs, many=True).data
    
    def get_total_earned(self, obj):
        txs = Transaction.objects.filter(tx_type="payout", wallet=obj)

        return txs.aggregate(total=Sum('amount'))["total"] or 0

class VerifyPaymentSerializer(serializers.Serializer):
    transaction_id = serializers.UUIDField(help_text="payment transaction id gotten from the payment initialization")
    