# Generated by Django 5.2.7 on 2026-04-09 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
    ]
