"""
Django settings for trimlybackend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k9&toki9k%@59k6jxkq_0s)zy31wl0k9-3yz^@1a)d^p+=80t9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api.v1.Salons',
    'api.v1.Bookings',
    'api.v1.Category',
    'api.v1.Chat',
    'api.v1.Payments',
    'api.v1.Reviews',
    'api.v1.Users',
    'api.v1.Vendor',
    'api.v1.Search',
    'funcs',
    'silk',


    #third party packages
    
    'channels',
    'rest_framework',
    'django.contrib.sites', 
    #Authentication Packages
    'rest_framework_simplejwt', # The token generator/validator
    'allauth', # Core for registration/verification
    'allauth.account', # Specific allauth module
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'dj_rest_auth', # The wrapper for DRF endpoints
    'dj_rest_auth.registration', # Registration module,
    'drf_spectacular',
    'django_filters',
    'cloudinary_storage',
    'cloudinary',
    'anymail',

    

]

ASGI_APPLICATION = 'trimlybackend.asgi.application'
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)], # Memurai default port
        },
    },
}

SITE_ID = 1 
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
    }
}
MIDDLEWARE = [
    # 'silk.middleware.SilkyMiddleware',
    'funcs.middleware.ResponseTimeMiddleware',
    'funcs.middleware.DBQueryCountMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'trimlybackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'trimlybackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import dj_database_url
import os
from dotenv import load_dotenv

load_dotenv()  

DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv("DATABASE_URL"),
        conn_max_age=60,
        ssl_require=True
    )
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'Users.User'
# CORS_ALLOWED_ORIGINS = ["*"]                 
CORS_ORIGIN_ALLOW_ALL =True
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = [
    "https://*.onrender.com",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    'https://interconfessional-erna-unheaded.ngrok-free.dev'
]
# ALLOWED_HOSTS = ['.ngrok-free.dev', 'localhost', '127.0.0.1']

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=90),
    'ROTATE_REFRESH_TOKENS': True,
    'SIGNING_KEY': os.getenv("SIGNING_KEY", "key"), 
    'AUTH_HEADER_TYPES': ('Bearer',), 
}
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'api.v1.utils.authentication.CsrfExemptSessionAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser', # <--- This allows images!
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100
}

# =========================
# DJANGO ALLAUTH SETTINGS
# =========================

# LOGIN WITH EMAIL ONLY
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_USER_MODEL_USERNAME_FIELD = None  # keep it
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False

ACCOUNT_SIGNUP_FIELDS = [
    'email*',
    'password1*',
    'password2*',
]
ACCOUNT_EMAIL_VERIFICATION_BY_CODE_ENABLED = True
ACCOUNT_LOGIN_BY_CODE_ENABLED = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_ADAPTER = 'trimlybackend.adapters.BackgroundEmailAdapter'

# Don't send allauth's default emails
ACCOUNT_EMAIL_CONFIRMATION_HMAC = False
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 1

REST_AUTH = {
    # 1. CRITICAL: Tells dj-rest-auth to issue JWTs instead of basic tokens
    'USE_JWT': True, 
    'TOKEN_MODEL': None,
    # 2. Use simplejwt's serializers to return the Access/Refresh token pair
    'JWT_AUTH_REFRESH_COOKIE': 'refresh_token', # Optional: Use cookie for refresh token
    'JWT_AUTH_HTTPONLY': True, # Optional security enhancement
    'TOKEN_SERIALIZER': 'dj_rest_auth.serializers.JWTSerializer',
    'USER_MODEL': 'Users.User',
    'REGISTER_SERIALIZER': 'api.v1.Users.serializers.CustomRegisterSerializer',
    'USER_DETAILS_SERIALIZER': 'api.v1.Users.serializers.UserDetailSerializer',
    'LOGIN_SERIALIZER': 'api.v1.Users.serializers.EmailLoginSerializer',
}



# # For development: uses mailbox sandbox
EMAIL_BACKEND = "anymail.backends.mailtrap.EmailBackend" 
# # Mailtrap Sandbox SMTP Credentials
# EMAIL_HOST = 'sandbox.smtp.mailtrap.io'
# EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")   # From Mailtrap Inbox Settings
# EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")  # From Mailtrap Inbox Settings
# EMAIL_PORT = os.getenv("EMAIL_PORT")
# EMAIL_USE_TLS = True
# EMAIL_USE_SSL = False

# This can be anything in Sandbox mode
DEFAULT_FROM_EMAIL = "Trimly <support@trimly.app>"
ANYMAIL = {
    "MAILTRAP_API_TOKEN": "ade4aa48e3f33bf64ef6c6fb3ccf391d",
    "MAILTRAP_SANDBOX_ID": "2931144", # From your Inbox URL
}

# IMPORTANT: Even with the API, Mailtrap Sandbox usually lets you 
# skip domain verification, but you MUST use the token found 
# specifically in the 'Inbox Settings' -> 'API' tab, NOT the general 'API Tokens' tab.

# In production, you would replace this with something like:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
SPECTACULAR_SETTINGS = {
    'TITLE': 'Trimly Backend API', # Your project's title
    'DESCRIPTION': 'API documentation for the Trimly backend services, including authentication and user management.',
    'VERSION': '1.0.0',
    # OTHER RECOMMENDED SETTINGS:
    'SERVE_INCLUDE_SCHEMA': False, # Schema is served separately
    # 'SWAGGER_UI_DIST': 'SIDECAR'
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,
        # This is the magic line that fixes CSRF
        "withCredentials": True, 
        
    },
    'SCHEMA_PATH_PREFIX': r'/api/v[0-9]/',
}


# This tells Django: "If the Google email matches an existing user, 
# just log them into that account instead of crashing/erroring."
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
FLW_SECRET_HASH = os.getenv("FLW_SECRET_HASH")
FLW_SECRET_KEY = os.getenv("FLW_SECRET_KEY")

SILKY_PYTHON_PROFILER = True
SILKY_MAX_RECORDED_REQUESTS = 1000
SILKY_MAX_RECORDED_REQUESTS_CHECK_PERCENT = 10
SILKY_SAVE_BODY = False  # <--- This is the big one! Stop saving huge JSON blobs.
