"""
Django settings for trimlybackend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import os
from dotenv import load_dotenv  
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = [
    "api.trimly.africa",
    "trimly-app.onrender.com",
    "localhost",
    "127.0.0.1",
]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api.v1.Salons',
    'api.v1.Bookings',
    'api.v1.Category',
    'api.v1.Chat',
    'api.v1.Payments',
    'api.v1.Reviews',
    'api.v1.Users',
    'api.v1.Vendor',
    'api.v1.Search',
    'api.v1.Notifications',
    # 'silk',


    #third party packages
    
    'channels',
    'django.contrib.gis',
    'rest_framework',
    'django.contrib.sites', 
    #Authentication Packages
    'rest_framework_simplejwt', # The token generator/validator
    'allauth', # Core for registration/verification
    'allauth.account', # Specific allauth module
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'dj_rest_auth', # The wrapper for DRF endpoints
    'dj_rest_auth.registration', # Registration module,
    'drf_spectacular',
    'django_filters',
    'cloudinary_storage',
    'cloudinary',
    'anymail',

    

]

ASGI_APPLICATION = 'trimlybackend.asgi.application'
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)], # Memurai default port
        },
    },
}

SITE_ID = 1 
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
    }
}
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'trimlybackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'trimlybackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import dj_database_url

# 1. Parse the URL from your environment
db_config = dj_database_url.config(
    default=os.getenv("DATABASE_URL"),
    # Set to 0 to immediately release connections back to the pooler
    # This is critical for Supabase Free Tier
    conn_max_age=0, 
    ssl_require=True
)

# 2. Force the PostGIS engine for your Salon/Marketplace geography fields
db_config['ENGINE'] = 'django.contrib.gis.db.backends.postgis'

# 3. Add specific timeouts to prevent "hanging" connections
db_config['OPTIONS'] = {
    'connect_timeout': 20,
}

DATABASES = {
    'default': db_config
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'Users.User'
# CORS_ALLOWED_ORIGINS = ["*"]                 
CORS_ORIGIN_ALLOW_ALL =True
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = [
    "https://*.onrender.com",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    'https://interconfessional-erna-unheaded.ngrok-free.dev'
]
# ALLOWED_HOSTS = ['.ngrok-free.dev', 'localhost', '127.0.0.1']
ALLOWED_HOSTS = ['*']

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'api.v1.utils.authentication.CsrfExemptSessionAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser', # <--- This allows images!
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

# =========================
# DJANGO ALLAUTH SETTINGS
# =========================

# LOGIN WITH EMAIL ONLY
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False

ACCOUNT_SIGNUP_FIELDS = [
    'email*',
    'password1*',
    'password2*',
]
ACCOUNT_EMAIL_VERIFICATION_BY_CODE_ENABLED = False
ACCOUNT_LOGIN_BY_CODE_ENABLED = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_ADAPTER = 'trimlybackend.adapters.NoEmailAdapter'

ACCOUNT_EMAIL_CONFIRMATION_HMAC = False
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 0

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=90),
    'ROTATE_REFRESH_TOKENS': True,
    'SIGNING_KEY': os.getenv("SIGNING_KEY", "key"), 
    'AUTH_HEADER_TYPES': ('Bearer',), 
}

# dj-rest-auth Configuration
REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_HTTPONLY': False,  # JSON response, not cookies
    'TOKEN_MODEL': None,
    
    'TOKEN_SERIALIZER': 'dj_rest_auth.serializers.JWTSerializer',
    'USER_MODEL': 'Users.User',
    'REGISTER_SERIALIZER': 'api.v1.Users.serializers.CustomRegisterSerializer',
    'USER_DETAILS_SERIALIZER': 'api.v1.Users.serializers.UserDetailSerializer',
    'LOGIN_SERIALIZER': 'api.v1.Users.serializers.EmailLoginSerializer',
}



# # For development: uses mailbox sandbox

## settings.py

ANYMAIL = {
    "RESEND_API_KEY": os.getenv("RESEND_API_KEY"),
}

DEFAULT_FROM_EMAIL = 'Trimly <noreply@trimly.africa>'
DEV_EMAIL_REDIRECT = os.getenv('DEV_EMAIL_REDIRECT', '')

# if os.getenv('DJANGO_ENV') == 'development':
#     EMAIL_BACKEND = 'api.v1.Core.email_backend.SandboxEmailBackend'
# else:
#     EMAIL_BACKEND = 'anymail.backends.resend.EmailBackend'

EMAIL_BACKEND = 'anymail.backends.resend.EmailBackend'


# IMPORTANT: Even with the API, Mailtrap Sandbox usually lets you 
# skip domain verification, but you MUST use the token found 
# specifically in the 'Inbox Settings' -> 'API' tab, NOT the general 'API Tokens' tab.

# In production, you would replace this with something like:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
SPECTACULAR_SETTINGS = {
    'TITLE': 'Trimly Backend API', # Your project's title
    'DESCRIPTION': 'API documentation for the Trimly backend services, including authentication and user management.',
    'VERSION': '1.0.0',
    # OTHER RECOMMENDED SETTINGS:
    'SERVE_INCLUDE_SCHEMA': False, # Schema is served separately
    # 'SWAGGER_UI_DIST': 'SIDECAR'
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,
        # This is the magic line that fixes CSRF
        "withCredentials": True, 
        
    },
    'SCHEMA_PATH_PREFIX': r'/api/v[0-9]/',
}


# This tells Django: "If the Google email matches an existing user, 
# just log them into that account instead of crashing/erroring."
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
FLW_SECRET_HASH = os.getenv("FLW_SECRET_HASH")
FLW_SECRET_KEY = os.getenv("FLW_SECRET_KEY")


import os



if os.name == 'nt':  # Windows
    GDAL_LIBRARY_PATH = r'C:\OSGeo4W\bin\gdal312.dll'
    GEOS_LIBRARY_PATH = r'C:\OSGeo4W\bin\geos_c.dll'
    
    # Add OSGeo4W to PATH
    osgeo_path = r'C:\OSGeo4W\bin'
    if osgeo_path not in os.environ['PATH']:
        os.environ['PATH'] = osgeo_path + ';' + os.environ['PATH']
# --- Celery Configuration ---

# 1. The "Broker" is where tasks are stored before a worker picks them up.
# Use your Memurai/Redis local address.
# settings.py
import os

# --- 1. CELERY CONFIG (Your "No-Worker" Hack) ---
# This allows tasks to run without a separate 'celery worker' process
CELERY_TASK_ALWAYS_EAGER = True 
CELERY_BROKER_URL = 'memory://'
CELERY_RESULT_BACKEND = None
CELERY_TIMEZONE = "UTC"
CELERY_TASK_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']

# --- 2. CHANNELS CONFIG (The "Switchboard" for Tabs) ---
# We need this to make sure Tab A can talk to Tab B
RENDER = os.environ.get('RENDER')

"""
Django settings for trimlybackend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import os
from dotenv import load_dotenv  
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "api.trimly.africa",
    "trimly-app.onrender.com",
    "localhost",
    "127.0.0.1",
]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api.v1.Salons',
    'api.v1.Bookings',
    'api.v1.Category',
    'api.v1.Chat',
    'api.v1.Payments',
    'api.v1.Reviews',
    'api.v1.Users',
    'api.v1.Vendor',
    'api.v1.Search',
    'api.v1.Notifications',
    # 'silk',


    #third party packages
    
    'channels',
    'django.contrib.gis',
    'rest_framework',
    'django.contrib.sites', 
    #Authentication Packages
    'rest_framework_simplejwt', # The token generator/validator
    'allauth', # Core for registration/verification
    'allauth.account', # Specific allauth module
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'dj_rest_auth', # The wrapper for DRF endpoints
    'dj_rest_auth.registration', # Registration module,
    'drf_spectacular',
    'django_filters',
    'cloudinary_storage',
    'cloudinary',
    'anymail',

    

]

ASGI_APPLICATION = 'trimlybackend.asgi.application'
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)], # Memurai default port
        },
    },
}

SITE_ID = 1 
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
    }
}
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'trimlybackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'trimlybackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import dj_database_url

# 1. Parse the URL from your environment
db_config = dj_database_url.config(
    default=os.getenv("DATABASE_URL"),
    # Set to 0 to immediately release connections back to the pooler
    # This is critical for Supabase Free Tier
    conn_max_age=0, 
    ssl_require=True
)

# 2. Force the PostGIS engine for your Salon/Marketplace geography fields
db_config['ENGINE'] = 'django.contrib.gis.db.backends.postgis'

# 3. Add specific timeouts to prevent "hanging" connections
db_config['OPTIONS'] = {
    'connect_timeout': 20,
}

DATABASES = {
    'default': db_config
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'Users.User'
# CORS_ALLOWED_ORIGINS = ["*"]                 
CORS_ORIGIN_ALLOW_ALL =True
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = [
    "https://*.onrender.com",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    'https://interconfessional-erna-unheaded.ngrok-free.dev'
]
# ALLOWED_HOSTS = ['.ngrok-free.dev', 'localhost', '127.0.0.1']
ALLOWED_HOSTS = ['*']

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'api.v1.utils.authentication.CsrfExemptSessionAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser', # <--- This allows images!
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

# =========================
# DJANGO ALLAUTH SETTINGS
# =========================

# LOGIN WITH EMAIL ONLY
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False

ACCOUNT_SIGNUP_FIELDS = [
    'email*',
    'password1*',
    'password2*',
]
ACCOUNT_EMAIL_VERIFICATION_BY_CODE_ENABLED = False
ACCOUNT_LOGIN_BY_CODE_ENABLED = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_ADAPTER = 'trimlybackend.adapters.NoEmailAdapter'

ACCOUNT_EMAIL_CONFIRMATION_HMAC = False
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 0

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=90),
    'ROTATE_REFRESH_TOKENS': True,
    'SIGNING_KEY': os.getenv("SIGNING_KEY", "key"), 
    'AUTH_HEADER_TYPES': ('Bearer',), 
}

# dj-rest-auth Configuration
REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_HTTPONLY': False,  # JSON response, not cookies
    'TOKEN_MODEL': None,
    
    'TOKEN_SERIALIZER': 'dj_rest_auth.serializers.JWTSerializer',
    'USER_MODEL': 'Users.User',
    'REGISTER_SERIALIZER': 'api.v1.Users.serializers.CustomRegisterSerializer',
    'USER_DETAILS_SERIALIZER': 'api.v1.Users.serializers.UserDetailSerializer',
    'LOGIN_SERIALIZER': 'api.v1.Users.serializers.EmailLoginSerializer',
}



# # For development: uses mailbox sandbox

## settings.py

ANYMAIL = {
    "RESEND_API_KEY": os.getenv("RESEND_API_KEY"),
}

DEFAULT_FROM_EMAIL = 'Trimly <noreply@trimly.africa>'
DEV_EMAIL_REDIRECT = os.getenv('DEV_EMAIL_REDIRECT', '')

# if os.getenv('DJANGO_ENV') == 'development':
#     EMAIL_BACKEND = 'api.v1.Core.email_backend.SandboxEmailBackend'
# else:
#     EMAIL_BACKEND = 'anymail.backends.resend.EmailBackend'

EMAIL_BACKEND = 'anymail.backends.resend.EmailBackend'


# IMPORTANT: Even with the API, Mailtrap Sandbox usually lets you 
# skip domain verification, but you MUST use the token found 
# specifically in the 'Inbox Settings' -> 'API' tab, NOT the general 'API Tokens' tab.

# In production, you would replace this with something like:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
SPECTACULAR_SETTINGS = {
    'TITLE': 'Trimly Backend API', # Your project's title
    'DESCRIPTION': 'API documentation for the Trimly backend services, including authentication and user management.',
    'VERSION': '1.0.0',
    # OTHER RECOMMENDED SETTINGS:
    'SERVE_INCLUDE_SCHEMA': False, # Schema is served separately
    # 'SWAGGER_UI_DIST': 'SIDECAR'
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,
        # This is the magic line that fixes CSRF
        "withCredentials": True, 
        
    },
    'SCHEMA_PATH_PREFIX': r'/api/v[0-9]/',
}


# This tells Django: "If the Google email matches an existing user, 
# just log them into that account instead of crashing/erroring."
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
FLW_SECRET_HASH = os.getenv("FLW_SECRET_HASH")
FLW_SECRET_KEY = os.getenv("FLW_SECRET_KEY")


import os



if os.name == 'nt':  # Windows
    GDAL_LIBRARY_PATH = r'C:\OSGeo4W\bin\gdal312.dll'
    GEOS_LIBRARY_PATH = r'C:\OSGeo4W\bin\geos_c.dll'
    
    # Add OSGeo4W to PATH
    osgeo_path = r'C:\OSGeo4W\bin'
    if osgeo_path not in os.environ['PATH']:
        os.environ['PATH'] = osgeo_path + ';' + os.environ['PATH']
# --- Celery Configuration ---

# 1. The "Broker" is where tasks are stored before a worker picks them up.
# Use your Memurai/Redis local address.
# settings.py
import os

# --- 1. CELERY CONFIG (Your "No-Worker" Hack) ---
# This allows tasks to run without a separate 'celery worker' process
CELERY_TASK_ALWAYS_EAGER = True 
CELERY_BROKER_URL = 'memory://'
CELERY_RESULT_BACKEND = None
CELERY_TIMEZONE = "UTC"
CELERY_TASK_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']

# --- 2. CHANNELS CONFIG (The "Switchboard" for Tabs) ---
# We need this to make sure Tab A can talk to Tab B
RENDER = os.environ.get('RENDER')

RENDER = os.environ.get('RENDER')

if RENDER:
    # PRODUCTION (No separate worker)
    REDIS_URL = os.environ.get('UPSTASH_REDIS_URL')
    CELERY_TASK_ALWAYS_EAGER = True  # Runs task in the same process
    CELERY_BROKER_URL = REDIS_URL 
else:
    # LOCAL (Testing with 'celery worker' terminal)
    REDIS_URL = 'redis://127.0.0.1:6379/0'
    CELERY_TASK_ALWAYS_EAGER = False # Sends task to Memurai for your worker to pick up
    CELERY_BROKER_URL = REDIS_URL

# Apply to Channels
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
        },
    },
}

# 4. Windows Specifics: Prevent common memory leaks/hangs
CELERY_WORKER_MAX_TASKS_PER_CHILD = 100 
 # Set to True for testing without a worker

# 5. Task discovery configuration
# This ensures Celery finds 'tasks.py' in all your apps automatically.
CELERY_IMPORTS = (
    'api.v1.Bookings.tasks', 
    'api.v1.Notifications.tasks'
)
# Safety check: Stop the app immediately if a secret is missing
if not os.getenv("RESEND_API_KEY"):
    raise ValueError("RESEND API KEY is not set in Render environment!")





# 4. Windows Specifics: Prevent common memory leaks/hangs
CELERY_WORKER_MAX_TASKS_PER_CHILD = 100 
 # Set to True for testing without a worker

# 5. Task discovery configuration
# This ensures Celery finds 'tasks.py' in all your apps automatically.
CELERY_IMPORTS = (
    'api.v1.Bookings.tasks', 
    'api.v1.Notifications.tasks'
)
# Safety check: Stop the app immediately if a secret is missing
if not os.getenv("RESEND_API_KEY"):
    raise ValueError("RESEND API KEY is not set in Render environment!")

DOJAH_APP_ID = os.getenv("DOJAH_APP_ID")
DOJAH_SECRET_KEY = os.getenv("DOJAH_SECRET_KEY")

FLW_V4_CLIENT_ID = os.getenv("FLW_V4_CLIENT_ID")
FLW_V4_CLIENT_SECRET = os.getenv("FLW_V4_CLIENT_SECRET")
FLW_V4_LIVE_BASE_URL = os.getenv("FLW_V4_LIVE_BASE_URL", "https://api.flutterwave.com")  # confirm exact live v4 host from docs


# --- Dojah API Settings ---
# Set 'production' in your server env vars, or default to 'sandbox' for dev
DOJAH_ENVIRONMENT = os.getenv("DOJAH_ENVIRONMENT", "sandbox")

DOJAH_APP_ID = os.getenv("DOJAH_APP_ID", "")
DOJAH_SECRET_KEY = os.getenv("DOJAH_SECRET_KEY", "")

