# Generated by Django 5.2.7 on 2026-02-13 15:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('category_id', models.IntegerField()),
                ('provider_type', models.CharField(max_length=10)),
                ('search_text', models.TextField()),
                ('avg_rating', models.FloatField()),
            ],
            options={
                'db_table': 'marketplace_view',
                'managed': False,
            },
        ),
    ]
