# Generated by Django 5.2.7 on 2025-12-08 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='package',
        ),
    ]
