# Generated by Django 5.2.7 on 2026-01-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0003_booking_payment_reference_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vendor_payout_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
