# Generated by Django 5.2.7 on 2026-02-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0005_alter_booking_date_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
    ]
