# Generated by Django 5.2.7 on 2025-12-03 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
        ('Salons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salonprofile',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salonprofile',
            name='portfolio',
            field=models.ManyToManyField(blank=True, to='Category.gallery'),
        ),
        migrations.AddField(
            model_name='salonprofile',
            name='salon_packages',
            field=models.ManyToManyField(blank=True, to='Salons.salonpackages'),
        ),
        migrations.AddField(
            model_name='salonpackages',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salons.salonprofile'),
        ),
        migrations.AddField(
            model_name='salonservices',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Category.servicecategory'),
        ),
        migrations.AddField(
            model_name='salonservices',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salons.salonprofile'),
        ),
        migrations.AddField(
            model_name='salonprofile',
            name='salon_services',
            field=models.ManyToManyField(blank=True, to='Salons.salonservices'),
        ),
        migrations.AddField(
            model_name='salonstaff',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salons.salonprofile'),
        ),
        migrations.AddField(
            model_name='salonstaff',
            name='service_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Category.servicecategory'),
        ),
        migrations.AddField(
            model_name='salonprofile',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Salons.salonstaff'),
        ),
    ]
