# Generated by Django 5.2.7 on 2025-12-20 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0003_initial'),
        ('Salons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salonownerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salonprofile',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Category.servicecategory'),
        ),
        migrations.AddField(
            model_name='salonprofile',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salonservices',
            name='categories',
            field=models.ManyToManyField(to='Category.servicecategory'),
        ),
        migrations.AddField(
            model_name='salonservices',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_services', to='Salons.salonprofile'),
        ),
        migrations.AddField(
            model_name='salonstaff',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_staff', to='Salons.salonprofile'),
        ),
        migrations.AddField(
            model_name='salonstaff',
            name='service_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Category.servicecategory'),
        ),
    ]
