# Generated by Django 5.2.7 on 2025-12-08 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [

        ('Category', '0001_initial'),
        ('Salons', '0003_salonservices_price_alter_salonpackages_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salonprofile',
            name='salon_packages',
        ),
        migrations.RemoveField(
            model_name='salonservices',
            name='category',
        ),
        migrations.RemoveField(
            model_name='salonservices',
            name='created_at',
        ),
        migrations.AddField(
            model_name='salonservices',
            name='categories',
            field=models.ManyToManyField(to='Category.servicecategory'),
        ),
        migrations.AddField(
            model_name='salonservices',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='salonservices',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='salonservices',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Salons.salonprofile'),
        ),
        migrations.CreateModel(
            name='SalonOwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='owners/')),
                ('address', models.CharField(max_length=255)),
                ('date_of_birth', models.DateTimeField(auto_now_add=True)),
                ('Gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SalonPackages',
        ),
    ]
