# Generated by Django 5.2.7 on 2025-12-08 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salons', '0004_remove_salonprofile_salon_packages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salonprofile',
            name='salon_services',
        ),
        migrations.RemoveField(
            model_name='salonprofile',
            name='specialist',
        ),
        migrations.AlterField(
            model_name='salonservices',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_services', to='Salons.salonprofile'),
        ),
        migrations.AlterField(
            model_name='salonstaff',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_staff', to='Salons.salonprofile'),
        ),
    ]
