# Generated by Django 5.2.7 on 2026-01-15 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salons', '0005_salonownerprofile_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonownerprofile',
            name='flw_subaccount_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
