# Generated by Django 5.2.7 on 2026-02-12 10:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salons', '0006_alter_salonownerprofile_flw_subaccount_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salonprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='salonprofile',
            name='longitude',
        ),
        migrations.AddField(
            model_name='salonprofile',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='salonprofile',
            name='tags',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
