# Generated by Django 5.2.7 on 2026-03-11 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salons', '0007_remove_salonprofile_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salonownerprofile',
            name='is_nin_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salonownerprofile',
            name='nin_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salonownerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salon_owner_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
