# Generated by Django 5.2.7 on 2026-01-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0003_wallet_transaction_withdrawalrequest_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='flw_ref',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('payout', 'Payout'), ('refund', 'Refund')], max_length=20),
        ),
    ]
