# Generated by Django 5.2.7 on 2026-01-15 22:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0004_transaction_flw_ref_alter_transaction_tx_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
