# Generated by Django 5.2.7 on 2026-03-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0005_alter_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='total_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
