# Generated by Django 5.2.7 on 2026-07-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0006_wallet_total_earned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='flw_transfer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
