# Generated by Django 5.2.7 on 2025-12-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualvendorprofile',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='individualvendorprofile',
            name='service_category',
        ),
        migrations.RemoveField(
            model_name='individualvendorprofile',
            name='worker',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('individual_vendor', 'Individual Vendor'), ('salon_owner', 'Salon Owner'), ('admin', 'admin')], default='customer', max_length=30),
        ),
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
        migrations.DeleteModel(
            name='IndividualVendorProfile',
        ),
    ]
