# Generated by Django 5.2.7 on 2026-03-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_nin_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='nin_last4',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nin_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
