# Generated by Django 5.2.7 on 2026-03-11 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_user_is_nin_verified_user_nin_last4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nin_last4',
        ),
    ]
