# Generated by Django 5.2.7 on 2026-03-20 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_alter_customerprofile_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='customer',
            new_name='user',
        ),
    ]
