# Generated by Django 5.2.7 on 2026-04-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_rename_customer_customerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='customer_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
